# app config
spring.application.name=medical-clinic-proxy
server.port=8081

# feign client config
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.cloud.openfeign.client.config.medicalclinicClient.url=http://medical-clinic:8080/

# actuator config
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true